services:
  telegram-bot:
    image: ghcr.io/goniz/telegram-claude-code:main
    container_name: telegram-bot
    restart: unless-stopped
    environment:
      - TELOXIDE_TOKEN=${TELOXIDE_TOKEN:?TELOXIDE_TOKEN is required}
      - RUST_LOG=${RUST_LOG:-debug,bollard=info}
      - DOCKER_HOST=${DOCKER_HOST:-unix:///var/run/docker.sock}
    # Mount logs directory for persistent logging and Docker socket for container management
    volumes:
      - ./logs:/app/logs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
