version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot
    restart: unless-stopped
    environment:
      - TELOXIDE_TOKEN=${TELOXIDE_TOKEN}
      - RUST_LOG=${RUST_LOG:-info}
    # Mount logs directory and Docker socket
    volumes:
      - ./logs:/app/logs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # Security options for Docker socket access
    user: "telegram-bot"
    group_add:
      - docker
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '1.0'
        reservations:
          memory: 128M
          cpus: '0.2'
    # Health check
    healthcheck:
      test: ["CMD", "pgrep", "-x", "telegram-bot"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Network for container isolation
    networks:
      - telegram-bot-network

  # Optional: Add a logging service for centralized log management
  log-aggregator:
    image: fluent/fluentd:v1.16-1
    container_name: telegram-bot-logs
    restart: unless-stopped
    volumes:
      - ./logs:/fluentd/log:ro
      - ./fluentd/conf:/fluentd/etc:ro
    ports:
      - "24224:24224"
    networks:
      - telegram-bot-network
    profiles:
      - logging

networks:
  telegram-bot-network:
    driver: bridge
    name: telegram-bot-network
