version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot
    restart: unless-stopped
    environment:
      - TELOXIDE_TOKEN=${TELOXIDE_TOKEN}
      - RUST_LOG=${RUST_LOG:-info}
    # Mount logs directory if you want to persist logs
    volumes:
      - ./logs:/app/logs:rw
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'
    # Health check
    healthcheck:
      test: ["CMD", "pgrep", "-x", "telegram-bot"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
