name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-rust:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        
    - name: Build
      run: cargo build --verbose
      
    - name: Test
      run: cargo test --verbose

  build-docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: docker build .

  test-docker-compose:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create test environment file
      run: |
        echo "TELOXIDE_TOKEN=test_token_for_ci" > .env
        echo "RUST_LOG=info" >> .env
        
    - name: Validate Docker Compose syntax
      run: docker compose -f docker-compose.test.yml config --quiet
      
    - name: Validate Docker Compose file structure
      run: |
        # Check that key sections exist and are properly configured
        docker compose -f docker-compose.test.yml config | grep -q "telegram-bot"
        docker compose -f docker-compose.test.yml config | grep -q "volumes"
        docker compose -f docker-compose.test.yml config | grep -q "healthcheck"
        docker compose -f docker-compose.test.yml config | grep -q "environment"
        echo "✅ Docker Compose structure validation passed"
        
    - name: Pull published image for testing
      run: |
        echo "Pulling published GitHub image for testing..."
        docker pull ghcr.io/goniz/telegram-claude-code:main || {
          echo "⚠️ Published image not available, this is expected for new repositories"
          echo "Using latest tag as fallback..."
          docker pull ghcr.io/goniz/telegram-claude-code:latest || {
            echo "⚠️ No published images available, skipping image-based tests"
            echo "This is expected for repositories without published images yet"
            exit 0
          }
        }
        
    - name: Test basic docker-compose operations
      run: |
        # Test that compose can parse and validate the configuration
        echo "Testing docker-compose configuration with published image..."
        docker compose -f docker-compose.test.yml config --services | grep -q telegram-bot
        echo "✅ Service configuration validation passed"
        
        # Test environment variable substitution
        if docker compose -f docker-compose.test.yml config | grep -q "test_token_for_ci"; then
          echo "✅ Environment variable substitution working"
        else
          echo "❌ Environment variable substitution failed"
          exit 1
        fi
        
        # Test that the image reference is correct
        if docker compose -f docker-compose.test.yml config | grep -q "ghcr.io/goniz/telegram-claude-code:main"; then
          echo "✅ Published image reference correct"
        else
          echo "❌ Published image reference not found"
          exit 1
        fi
        
    - name: Cleanup
      run: docker compose -f docker-compose.test.yml down --volumes --rmi local
      if: always()

  push-docker:
    runs-on: ubuntu-latest
    needs: [build-rust, build-docker, test-docker-compose]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=branch
          type=sha,prefix={{branch}}-
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}