name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-rust:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        
    - name: Build
      run: cargo build --verbose
      
    - name: Test
      run: cargo test --verbose

  build-docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: docker build .

  test-docker-compose:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create test environment file
      run: |
        echo "TELOXIDE_TOKEN=test_token_for_ci" > .env
        echo "RUST_LOG=info" >> .env
        
    - name: Validate Docker Compose syntax
      run: docker compose config --quiet
      
    - name: Test Docker Compose up
      run: |
        echo "Testing docker compose up..."
        # Use --wait to wait for services to be running, but expect health check to fail with test token
        if timeout 30s docker compose up -d --wait; then
          echo "✅ Container started successfully and is healthy"
        else
          # Check if container at least started (proving Docker setup works)
          if docker compose ps --format json | jq -r '.State' | grep -E "(running|restarting)"; then
            echo "✅ Container started successfully (health check failed as expected with test token)"
          else
            echo "❌ Container failed to start"
            docker compose logs
            docker compose down --volumes
            exit 1
          fi
        fi
        
        # Cleanup
        docker compose down --volumes

  push-docker:
    runs-on: ubuntu-latest
    needs: [build-rust, build-docker, test-docker-compose]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=branch
          type=sha,prefix={{branch}}-
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}